### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by KeelyDulmage** [milesjor/VAULT#1]
Hi! Very excited to try out VAULT.  I installed as directed and attempted to run VAULT from my conda env using the example code and get the following errors.
Code: 
>./vault -u CATCTTACGATTACGCCAACCACTGCGGNNNNNTGNNNNNGACACATTCTCCCAGGCCCTACTT -q ./example/nanopore_reads.fastq.gz -s ./example/result -r ./example/reference.fa -e 0.11 -a map-ont --minlength 300 --maxlength 20000 --unmapped_reads --group_filter -t 4 -b 1

Output:
>2021-03-15 15:41:56    --------- received arguments ---------
umi adapter:    CATCTTACGATTACGCCAACCACTGCGGNNNNNTGNNNNNGACACATTCTCCCAGGCCCTACTT
fastq file:     ./example/nanopore_reads.fastq.gz
refer file:     ./example/reference.fa
error rate:     0.11
align mode:     map-ont
thread:         12
save path:      ./example/result
2021-03-15 15:41:56    Start filtering reads by length 300 - 20000 ...
2021-03-15 15:41:56    Start extracting mapped reads ...
2021-03-15 15:41:56    Start extracting UMIs from reads ...
left_flank:   CATCTTACGATTACGCCAACCACTGCGG
umi:          NNNNNTGNNNNN
right_flank:  GACACATTCTCCCAGGCCCTACTT
/home/keelydulmage/VAULT/check_umi.sh: 6: /home/keelydulmage/VAULT/check_umi.sh: Syntax error: "(" unexpected
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/keelydulmage/anaconda2/envs/vault/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/keelydulmage/anaconda2/envs/vault/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/keelydulmage/VAULT/vault_main.py", line 173, in run_bash_cmd
    subprocess.run(cmd, shell=True, check=True, stdout=subprocess.PIPE)  # print only stderr to screen
  File "/home/keelydulmage/anaconda2/envs/vault/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'sh /home/keelydulmage/VAULT/check_umi.sh -n umi_analysis -l CATCTTACGATTACGCCAACCACTGCGG -u NNNNNTGNNNNN -r GACACATTCTCCCAGGCCCTACTT                  -q ./example/result/nanopore_reads.300-20000.mapped.fastq -s ./example/result -e 0.11 -t 6 -5' returned non-zero exit status 2.
/home/keelydulmage/VAULT/check_umi.sh: 6: /home/keelydulmage/VAULT/check_umi.sh: Syntax error: "(" unexpected
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/keelydulmage/anaconda2/envs/vault/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/keelydulmage/anaconda2/envs/vault/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/keelydulmage/VAULT/vault_main.py", line 173, in run_bash_cmd
    subprocess.run(cmd, shell=True, check=True, stdout=subprocess.PIPE)  # print only stderr to screen
  File "/home/keelydulmage/anaconda2/envs/vault/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'sh /home/keelydulmage/VAULT/check_umi.sh -n umi_analysis -l CATCTTACGATTACGCCAACCACTGCGG -u NNNNNTGNNNNN -r GACACATTCTCCCAGGCCCTACTT                  -q ./example/result/nanopore_reads.300-20000.mapped.fastq -s ./example/result -e 0.11 -t 6 -3' returned non-zero exit status 2.
2021-03-15 15:41:56    Extract UMIs from reads finished
Traceback (most recent call last):
  File "./vault", line 11, in <module>
    sys.exit(main())
  File "/home/keelydulmage/VAULT/vault_main.py", line 626, in main
    extract_name_lst(args)
  File "/home/keelydulmage/VAULT/vault_main.py", line 212, in extract_name_lst
    os.mkdir(end5 + '/reads_with_same_UMIs')
FileNotFoundError: [Errno 2] No such file or directory: './example/result/umi_analysis/5end_UMIs/reads_with_same_UMIs'

For reference I'm running this in Ubuntu 18.04.2 and anaconda2 with Python 3.6.10

**Comment by milesjor** [comment]
Hi Keely, thank you for testing the code. The UMI extraction step is not working in your run. VAULT utilize cutadapt version 2.7 to extract UMI sequences, if you used a different version, it may cause problems. If this is the case, you may remove cutadapt and install the correct version by 'conda install cutadapt=2.7'. 

otherwise, after getting this error message, could you please try the below code and let me know the output?
```
sh /home/keelydulmage/VAULT/check_umi.sh -n umi_analysis -l CATCTTACGATTACGCCAACCACTGCGG -u NNNNNTGNNNNN -r GACACATTCTCCCAGGCCCTACTT -q ./example/result/nanopore_reads.300-20000.mapped.fastq -s ./example/result -e 0.11 -t 6 -5
```

**Comment by KeelyDulmage** [comment]
Thanks for the rapid response! I upgraded cutadapt to 2.7 but am still getting an error:

 ```
(vault) keely.dulmage@computer:~$ cutadapt --version
2.7
(vault) keely.dulmage@computer:~$ sh ./VAULT/check_umi.sh -n umi_analysis -l CATCTTACGATTACGCCAACCACTGCGG -u NNNNNTGNNNNN -r GACACATTCTCCCAGGCCCTACTT -q ./example/result/nanopore_reads.300-20000.mapped.fastq -s ./example/result -e 0.11 -t 6 -5
./VAULT/check_umi.sh: 6: ./VAULT/check_umi.sh: Syntax error: "(" unexpected
```
I may try to install on another computer next week to make sure it's not just that server's conda config.

**Comment by milesjor** [comment]
I checked the code but didn't find the mentioned Syntax error "6: ./VAULT/check_umi.sh: Syntax error: "(" unexpected". Could you please delete your current VAULT folder and related conda environment, and make a fresh installation by
```
git clone https://github.com/milesjor/VAULT.git
cd ./VAULT/
conda env create --name vault --file ./tools/vault_env.yaml
conda activate vault
```

BTW, VAULT was tested on Ubuntu 18.04.5, Ubuntu 16.04.7, and macOS 14.06.6. Kindly let me know if you still have the issue.

**Comment by KeelyDulmage** [comment]
Hmmm, I followed your above instructions to reinstall and got the same error:
`check_umi.sh: 6: check_umi.sh: Syntax error: "(" unexpected`

Additionally, I thought maybe there might be something weird with my conda setup on the server, so I also installed vault on my local WSL (Ubuntu 18.04.2 LTS, anaconda3) and got the same error.

And here's the results from running the test code on my WSL installation: 
>(vault) keely@computer:~/VAULT$ ./vault -u CATCTTACGATTACGCCAACCACTGCGGNNNNNTGNNNNNGACACATTCTCCCAGGCCCTACTT \
         -q ./example/nanopore_reads.fastq.gz \
         -s ./example/result \
         -r ./example/reference.fa \
         -e 0.11 \
         -a map-ont \
         --minlength 300 \
         --maxlength 20000 \
         --unmapped_reads \
         --group_filter \
         -t 4 \
         -b 1
2021-03-22 09:24:27    --------- received arguments ---------
umi adapter:    CATCTTACGATTACGCCAACCACTGCGGNNNNNTGNNNNNGACACATTCTCCCAGGCCCTACTT
fastq file:     ./example/nanopore_reads.fastq.gz
refer file:     ./example/reference.fa
error rate:     0.11
align mode:     map-ont
thread:         4
save path:      ./example/result
2021-03-22 09:24:27    Start filtering reads by length 300 - 20000 ...
2021-03-22 09:24:27    Start extracting mapped reads ...
2021-03-22 09:24:27    Start extracting UMIs from reads ...
left_flank:   CATCTTACGATTACGCCAACCACTGCGG
umi:          NNNNNTGNNNNN
right_flank:  GACACATTCTCCCAGGCCCTACTT
/home/keely/VAULT/check_umi.sh: 6: /home/keely/VAULT/check_umi.sh: Syntax error: "(" unexpected
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/keely/anaconda3/envs/vault/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/keely/anaconda3/envs/vault/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/keely/VAULT/vault_main.py", line 56, in run_bash_cmd
    subprocess.run(cmd, shell=True, check=True, stdout=subprocess.PIPE)  # print only stderr to screen
  File "/home/keely/anaconda3/envs/vault/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'sh /home/keely/VAULT/check_umi.sh -n umi_analysis -l CATCTTACGATTACGCCAACCACTGCGG -u NNNNNTGNNNNN -r GACACATTCTCCCAGGCCCTACTT                  -q ./example/result/nanopore_reads.300-20000.mapped.fastq -s ./example/result -e 0.11 -t 2 -5' returned non-zero exit status 2.
/home/keely/VAULT/check_umi.sh: 6: /home/keely/VAULT/check_umi.sh:
Syntax error: "(" unexpected
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/keely/anaconda3/envs/vault/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/keely/anaconda3/envs/vault/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/keely/VAULT/vault_main.py", line 56, in run_bash_cmd
    subprocess.run(cmd, shell=True, check=True, stdout=subprocess.PIPE)  # print only stderr to screen
  File "/home/keely/anaconda3/envs/vault/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'sh /home/keely/VAULT/check_umi.sh -n umi_analysis -l CATCTTACGATTACGCCAACCACTGCGG -u NNNNNTGNNNNN -r GACACATTCTCCCAGGCCCTACTT                  -q ./example/result/nanopore_reads.300-20000.mapped.fastq -s ./example/result -e 0.11 -t 2 -3' returned non-zero exit status 2.
2021-03-22 09:24:27    Extract UMIs from reads finished
Traceback (most recent call last):
  File "./vault", line 11, in <module>
    sys.exit(main())
  File "/home/keely/VAULT/vault_main.py", line 509, in main
    extract_name_lst(args)
  File "/home/keely/VAULT/vault_main.py", line 95, in extract_name_lst
    os.mkdir(end5 + '/reads_with_same_UMIs')
FileNotFoundError: [Errno 2] No such file or directory: './example/result/umi_analysis/5end_UMIs/reads_with_same_UMIs'

**Comment by milesjor** [comment]
Sorry for the late reply. The error is probably due to the issue of your shell interpreter, however, I can't reproduce your error in my workstation. Anyway, I revised the code to avoid the problematic line. Could you please update your VAULT to the latest version and try again with the same command?

If it failed again, please try adding  '--py_only' in the command as shown below. I wrapped the bash script in python under this mode. Kindly let me know the result.

>./vault -u CATCTTACGATTACGCCAACCACTGCGGNNNNNTGNNNNNGACACATTCTCCCAGGCCCTACTT -q ./example/nanopore_reads.fastq.gz -s ./example/result -r ./example/reference.fa -e 0.11 -a map-ont --minlength 300 --maxlength 20000 --unmapped_reads --group_filter -t 4 -b 1 --py_only

**Comment by KeelyDulmage** [comment]
It's working now! 
> (vault) keely.dulmage@computer:~/VAULT$ ./vault -u CATCTTACGATTACGCCAACCACTGCGGNNNNNTGNNNNNGACACATTCTCCCAGGCCCTACTT -q ./example/nanopore_reads.fastq.gz -s ./example/result -r ./example/reference.fa -e 0.11 -a map-ont --minlength 300 --max
length 20000 --unmapped_reads --group_filter -t 4 -b 1

```
2021-03-29 09:40:57    --------- received arguments ---------
umi adapter:    CATCTTACGATTACGCCAACCACTGCGGNNNNNTGNNNNNGACACATTCTCCCAGGCCCTACTT
fastq file:     ./example/nanopore_reads.fastq.gz
refer file:     ./example/reference.fa
error rate:     0.11
align mode:     map-ont
thread:         4
save path:      ./example/result

2021-03-29 09:40:57    Start filtering reads by length 300 - 20000 ...
2021-03-29 09:40:57    Start extracting mapped reads ...
2021-03-29 09:40:57    Start extracting UMIs from reads ...

left_flank:   CATCTTACGATTACGCCAACCACTGCGG
umi:          NNNNNTGNNNNN
right_flank:  GACACATTCTCCCAGGCCCTACTT

2021-03-29 09:40:58    Extract UMIs from reads finished
2021-03-29 09:40:58    Group reads by UMIs finished
2021-03-29 09:40:58    Start individual UMI group analysis ...
2021-03-29 09:41:37    5'+3' and 5' end UMI analysis finished
2021-03-29 09:41:59    The rest 3' end UMI analysis finished

2021-03-29 09:41:59    ------------ Jobs done! ------------
```
Just out of curiosity I DID try it with --py_only enabled, which actually causes it to fail.  I can post that error if you are interested.  Otherwise, thank you very much for troubleshooting this, I look forward to trying it on real data at some point.
